project:
  type: book
  output-dir: _site

book:
  title: "The Energy Modeller’s Compass"
  subtitle: "Decision-support modelling for energy systems"
  author: "Andrés Ramos and Diego Tejada"
  site-url: "https://iit-energysystemmodels.github.io/COMPASS/"
  repo-url: "https://github.com/IIT-EnergySystemModels/COMPASS"
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - chapters/01-introduction/index.qmd
    - chapters/02-economic-dispatch/index.qmd
    - chapters/02-economic-dispatch/index-examples-in-python.qmd
    - chapters/02-economic-dispatch/index-examples-in-julia.qmd
    - chapters/03-unit-commitment/index.qmd
    - chapters/04-stochastic-optimisation/index.qmd
    - chapters/05-hydrothermal-scheduling/index.qmd
    - chapters/06-generation-expansion-planning/index.qmd
    - chapters/07-decomposition-methods/index.qmd
    - chapters/08-network-constrained/index.qmd
    - chapters/09-transmission-expansion-planning/index.qmd
    - chapters/10-trade-off-modelling/index.qmd
    - chapters/11-advanced-topics/index.qmd
    - chapters/references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    number-sections: true
    code-copy: true
    code-overflow: wrap

execute:
  echo: true
  warning: false
  message: false
  freeze: auto
  cache: true
  execute-dir: project
